version: '3.1'

services:
  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: poire
      MARIADB_DATABASE: chess_pomme
      MARIADB_USER: pomme
      MARIADB_PASSWORD: pomme
    volumes:
      - ./db:/var/lib/mysql
      - ./model/db.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
  chess_pomme:
    image: chesspomme
    ports:
      - '80:8080'
    depends_on:
      - mariadb
    restart: always
